### ISSUE TITLE
Houdini shelf tool updater

### ISSUE THREAD

**Issue by nrdpxl** [toadstorm/MOPS#164]
Hello guys, reporting an issue here. Shelf tool: MOP's updater returned an error:
Screenshot: https://www.dropbox.com/s/e25i6uenatwfoog/Screenshot%202019-03-22%2007.34.42.png?dl=0

`
Traceback (most recent call last):
  File "MOPS_Update", line 341, in <module>
  File "MOPS_Update", line 229, in __init__
  File "MOPS_Update", line 67, in get_releases
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/Applications/Houdini/Houdini17.5.173/Frameworks/Python.framework/Versions/Current/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
`

**Comment by toadstorm** [comment]
I can't replicate this issue. Can you tell me more about your system? Are you operating behind a firewall or VPN/proxy?

**Comment by nrdpxl** [comment]
I'm on macOS 10.14.3 (Mojave), I can confirm, that there is an issue on Linux (CentOS 7.6 too) and can replicate problem on both.
It was similar issue with GameDev tools too but hey fixed that check it here:
https://www.dropbox.com/s/czpa3ocxu15l1ui/gamedevtools.png?dl=0

**Comment by toadstorm** [comment]
Okay, I just had a chat with the GameDev guys and they shared their fix. I'll implement this as soon as I have a free minute, it should be an easy one.

**Comment by toadstorm** [comment]
Hey, the latest Experimental build should fix this problem. Do you mind downloading it manually and testing it for us?

**Comment by nrdpxl** [comment]
Hey, thanks for an update. I can confirm macOS version is fixed, on linux side I have weird GUI issues but functionality works:
https://www.dropbox.com/s/u8k1jeeu5adfs51/Screenshot%20from%202019-04-05%2008-14-47.png?dl=0

I can't choose 'experimental' version on dialog, so when I press update or "pply Updat" it drops back to stable release and brakes the updater. Anyway won't be an issue when these changes will go downstream to the "stable' branch. No one uses linux anyway ;)

**Comment by toadstorm** [comment]
The UI scaling thing has been a real pain in the ass when designing Qt dialogs... apparently my controls won't properly inherit that part of Houdini's main .QSS style sheet. I'll have to look into it more; thanks for testing. I'll close this specific issue in the meantime.
